############ Agent Config ############
agent:
  rpc_url: http://127.0.0.1:8215
  action_url: sharder
  upload_size: 5 * 1024 * 1024
############ System Config ############
server:
  port: 8088
  tomcat:
    max-http-post-size: -1
#ssl.key-store: classpath:keystore.jks
#ssl.key-store-password : 000000
#ssl.key-password: 000000
spring:
  servlet:
    multipart:
      enabled: false
      max-file-size: 5MB
      max-request-size: 10MB

######### Predefined Peers Config ##########
peers:
  list:
    - address: 127.0.0.1
      uri: http://127.0.0.1:8215
      type: 1